language: ruby

rvm:
    - "2.1.0"

secure: "egxZBZqXhgKpV0rxXSinymvxQc70Y41Z7N5QvouMLXc8o2ydC7alV7k8OvdF6gwY+rOQqOtGYDW3nwem/wSSa3hU5Vv5+5Z2jDKZ0R40Ojkbj7Ma/jTIfYBGRhu+jkPBNIb5gOHddTbavkyASxSFNpDoTyOir90Z+EWR0Tm8pI8="

before_script:
  - "psql -c 'create role sample_app_3_2 SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database sample_app_3_2_test;' -U postgres postgres"
  - "bundle exec rake db:migrate"
